services:
  mysql:
    image: mysql:8.1
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: StrongPass123!
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/mysql_dump.sql/mysql_dump.sql:/docker-entrypoint-initdb.d/mysql_dump.sql:ro

volumes:
  mysql-data:
